# security 使能
#security.basic.enabled = false
spring:
  datasource:
    username: xuexiao
    password: xuexiao
    url: jdbc:mysql://39.105.45.15:3306/xuexiao?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai

  thymeleaf:
    enabled: true
    cache: false #禁用缓存
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: html
  mvc:
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
